//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorinneCity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Minute
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileBytes { get; set; }
        public int FileType { get; set; }
        public string FileContent { get; set; }
        public string Year { get; set; }
    }
}
